language: java
sudo: true
addons:
  sauce_connect:
    username: "N00bface"
    access_key: "fbe21e01-aeb0-46ef-baab-b5e4aafc3b7b"
before_install:
  - chmod a+x install.sh

jdk:
  - oraclejdk8

install: ./install.sh